/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as lib from "./lib";
export { Will__factory } from "./Will__factory";
export { WillFactory__factory } from "./WillFactory__factory";
