/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lib from "./lib";
export type { lib };
export type { Will } from "./Will";
export type { WillFactory } from "./WillFactory";
export * as factories from "./factories";
export type { ERC20 } from "./lib/ERC20";
export { ERC20__factory } from "./factories/lib/ERC20__factory";
export type { IERC20 } from "./lib/IERC20";
export { IERC20__factory } from "./factories/lib/IERC20__factory";
export type { IERC20Permit } from "./lib/IERC20Permit";
export { IERC20Permit__factory } from "./factories/lib/IERC20Permit__factory";
export { Will__factory } from "./factories/Will__factory";
export { WillFactory__factory } from "./factories/WillFactory__factory";
